export const COLLECTIONS = Object.freeze({
  USERS: 'users',
  PATIENTS: 'patients',
  PARTNERS: 'partners',
  REFERRAL_CODES: 'referralCodes',
  REFERRALS: 'referrals',
  COMMISSIONS: 'commissions',
  CASES: 'cases',
  HOSPITALS: 'hospitals',
  DOCTORS: 'doctors',
  TREATMENTS: 'treatments',
  DESTINATIONS: 'destinations',
  TREATMENT_PLANS: 'treatmentPlans',
  CONSULTATIONS: 'consultations',
  COORDINATORS: 'coordinators',
  CONSENTS: 'consents',
  CASE_CONSENT_STATES: 'caseConsentStates',
  CASE_MESSAGES: 'caseMessages',
  NOTIFICATIONS: 'notifications',
  AUDIT_LOGS: 'auditLogs'
});
