import { BadgeCheck, Building2, CheckCircle2, Globe2, Languages, MapPin, ShieldCheck } from 'lucide-react';
import HospitalShell from '@/components/HospitalShell';

export const metadata = { title: 'Hospital Profile — CareAtlas Partner Portal' };

export default function HospitalProfilePage(){
  return <HospitalShell title="Hospital profile" subtitle="Preview the information patients use when comparing Aster Nova Institute.">
    <div className="hospital-profile-admin-grid"><section className="portal-card partner-profile-card"><div className="partner-profile-cover"></div><div className="partner-profile-content"><div className="partner-profile-logo"><Building2 size={26}/></div><span className="verified-line"><BadgeCheck size={15}/> Demo verified partner</span><h2>Aster Nova Institute</h2><p><MapPin size={14}/> New Delhi, India</p><div className="partner-profile-tags"><span>Orthopedics</span><span>Cardiology</span><span>Oncology</span><span>Neurology</span></div></div></section><section className="portal-card profile-completeness"><span className="eyebrow">PROFILE HEALTH</span><div className="completeness-score">88<small>%</small></div><h3>Strong international profile</h3><p>Patients make better comparisons when treatment costs, doctor availability, accreditations and international services stay current.</p><div className="profile-checks"><span><CheckCircle2 size={14}/> Hospital overview</span><span><CheckCircle2 size={14}/> International services</span><span><CheckCircle2 size={14}/> Clinical team</span><span><ShieldCheck size={14}/> Accreditation verification pending production</span></div></section></div>
    <div className="profile-admin-sections"><section className="portal-card"><span className="eyebrow">INTERNATIONAL DESK</span><div className="profile-detail-grid"><span><Globe2 size={17}/><small>Countries supported</small><strong>80+ demo value</strong></span><span><Languages size={17}/><small>Languages</small><strong>English · Hindi · Arabic support</strong></span><span><ShieldCheck size={17}/><small>Response target</small><strong>Within 12 hours</strong></span></div></section><section className="portal-card"><span className="eyebrow">PRODUCTION NOTE</span><p className="profile-production-note">Before launch, CareAtlas should verify hospital identity, legal entity, licenses/accreditations, authorized partner users and all patient-facing claims. Demo metrics currently shown on the public site must not be treated as verified facts.</p></section></div>
  </HospitalShell>;
}
